# This will load for all environments (its a base config - can be overridden by env specific configs)
spring:
   application:
      name: url-shortener

server:
   port: 7777
   
app:
  base-url: http://localhost:7777